"""Create stock_analytics table

Revision ID: 2b7889898e75
Revises: b63f7f5dbab9
Create Date: 2025-08-17 00:53:53.084722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b7889898e75'
down_revision: Union[str, Sequence[str], None] = 'b63f7f5dbab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_analytics',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('annualized_return', sa.Float(), nullable=True),
    sa.Column('annualized_volatility', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.PrimaryKeyConstraint('ticker', 'analysis_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_analytics')
    # ### end Alembic commands ###
